#Server Config
server:
  port: 8090

# Paging
blog:
  per:
    page:
      size: 10

spring:
  # Data Resource
  datasource:
    url: jdbc:mysql://125.186.242.83:8088/podo-dev?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: cglee079
    password: lcg050179!
    driver-class-name: com.mysql.jdbc.Driver

  # Hibernate config
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format: false

  # Servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Security
  security:
    user:
      name: cglee079
      password: s12345

logging:
  level:
    org:
      springframework:
        web: DEBUG


upload:
  base:
    url: /uploaded
    dir: C://podo-dev/upload
  postfix:
    file:
      dir: /blogs/files
    image:
      dir: /blogs/images


infra:
  uploader:
    domain: http://localhost:8092
    upload:
        subpath: /api/upload
    frontend:
      subpath: /uploaded


  telegram:
    podo:
      bot:
        token: 509885308:AAGqgiMXRfkXWeamsta6N0nFkF0d9I_SFOI
      user:
        name: PodoDevBot
        id: 503609560

  solr:
    url: http://125.186.242.83:8090/solr
    core:
      id: podo-dev
    query:
      hl:
        max:
          pre:
            length: 100
        frag:
          length : 10000000
        simple:
          pre: ((start-search))
          post: ((end-search))

