#Server Config
server.port: 28443
server.http.port: 28080

spring.profiles.include: ssl, core, jpa, infra, oauth, log

# Servlet
spring.servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB

## Blog Content Config
blog.page.size: 10
blog.relates.size: 5
blog.comment:
  page.size: 5
  max.depth: 3
  recent.size: 7


job:
  tempcleaner:
    expire_hours : 48


## File Save Config
local.static.dir: C://podo-dev/podo-dev-backend/static
local.upload:
    base.path: /uploaded
    base.dir: C://podo-dev/podo-dev-backend/uploaded
    sub.file.dir: /blogs/files
    sub.image.dir: /blogs/images

---
spring.profiles: test

#spring.cache.type: NONE

---
spring.profiles: deploy

server.port: 8443
server.http.port: 8080
local.static.dir: /static
local.upload.base.dir: /uploaded





