#Server Config
server:
  port: 8090

# Paging
blog:
  per:
    page:
      size: 10

spring:
  profiles:
    include: 'core'

  # Data Resource
  datasource:
    url: jdbc:mysql://125.186.242.83:8088/podo-dev?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: cglee079
    password: lcg050179!
    driver-class-name: com.mysql.jdbc.Driver

  # Hibernate config
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format: false

  # Servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#  # Security
#  security:
#    user:
#      name: cglee079
#      password: s12345

upload:
  base:
    url: /uploaded
    dir: C://podo-dev/upload
  postfix:
    file:
      dir: /blogs/files
    image:
      dir: /blogs/images


infra:
  uploader:
    token: mciGpOzzSvncQJ5IFEUNVODRyVkgL1kD
    domain: http://125.186.242.83:8090
    upload:
      subpath: /api/uploader/file
    frontend:
      subpath: /uploaded


  telegram:
    podo:
      bot:
        token: 509885308:AAGqgiMXRfkXWeamsta6N0nFkF0d9I_SFOI
        name: PodoDevBot
      admin:
        id: 503609560

  solr:
    url: http://125.186.242.83:8090/solr
    core:
      id: podo-dev
    query:
      hl:
        pre:
          max:
            length: 100
        frag:
          length: 10000000
        simple:
          pre: ((start-search))
          post: ((end-search))

google:
  client:
    clientId: 644014618387-hd23qa0hrtqvbtnfb0u3c9o9q9duq970.apps.googleusercontent.com
    clientSecret: RxNajOBGU8TZtR-zc9pOu6uG
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

security:
  expire:
    time: 24 # Hours
  oauth2:
    admin:
      ids: 116440278738014640765, 116491882380204991899
    redirect: http://localhost:8080
