#Server Config
server:
  port: 28443
  http:
    port: 28080


## Log
logging:
  file: podo-dev-backend.%d{yyyy-MM-dd}-%i.log
  path: c://podo-dev/podo-dev-backend/logs

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: false
      logging: slf4j
      #log-file: spy.log
      #log-format: # custom log format


spring:
  profiles:
    include: secret, core

  # Hibernate config
  jpa:
    database: MYSQL
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        fomat_sql: true
        #        show_sql: true
        default_batch_fetch_size: 20
    open-in-view: false


  # Servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

## Blog Content Config
blog:
  relates:
    size: 5
  comment:
    page:
      size: 5 # Comment Paging Size
    max:
      depth: 3 # Comment Max Reply Depth
    recent:
      size: 10
  page:
    size: 10 # Blog Paging Size


## File Save Config
local:
  static:
    dir: C://podo-dev/podo-dev-backend/static
  upload:
    base:
      path: /uploaded
      dir: C://podo-dev/podo-dev-backend/uploaded
    sub:
      file:
        dir: /blogs/files
      image:
        dir: /blogs/images

infra:
  storage:
    server:
      internal: http://192.168.219.103:38080/api/file # Loopback
    static:
      internal: http://192.168.219.103:30080
      external: https://file.podo-dev.com
  #      external: https://static.podo-dev.com

  telegram:
    admin:
      telegram_id: 503609560
    bot:
      name: PodoDevBot

  solr:
    url: http://192.168.219.103:8979/solr # Loopback
    core_id: podo-dev
    highlight:
      pre_max_text_length: 100
      frag:
        length: 10000000

security:
  oauth2:
#    redirect: http://localhost:3000
    redirect: https://www.podo-dev.com

---

spring:
  profiles: deploy
  jpa:
    show-sql: false

server:
  port: 8443
  http:
    port: 8080

## Log
logging:
  path: /data/logs

decorator:
  datasource:
    p6spy:
      enable-logging: false

local:
  static:
    dir: /static
  upload:
    base:
      dir: /uploaded

security:
  oauth2:
    redirect: https://www.podo-dev.com



