#Server Config
server:
  port: 28443
  http:
    port : 28080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: s12345
    keyStoreType: PKCS12
    keyAlias: tomcat


logging:
  #  file: logs/application.log
  level:
    root: INFO



spring:
  profiles:
#    include: core
      include: core, deploy

  # Data Resource
  datasource:
    url: jdbc:mysql://192.168.219.103:3307/podo_dev?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: podo
    password: s12345
    driver-class-name: com.mysql.jdbc.Driver

  # Hibernate config
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format: false

  # Servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

## Blog Content Config
blog:
  comment:
    per:
      page:
        size: 5 # Comment Paging Size
    max:
      depth: 3 # Comment Max Reply Depth
  per:
    page:
      size: 10 # Blog Paging Size


## File Save Config
local:
  web:
    url: /web
    dir: C://podo-dev/web
  upload:
    base:
      url: /uploaded
      dir: C://podo-dev/uploaded
    sub:
      file:
        dir: /blogs/files
      image:
        dir: /blogs/images



infra:

  ## Uploader Config
  uploader:
    token: mciGpOzzSvncQJ5IFEUNVODRyVkgL1kD
    domain:
      internal: http://192.168.219.103:38080 # Loopback
      external : https://upload.podo-dev.com
    upload:
      subpath: /api/uploader/file
    frontend:
      subpath: /uploaded


  ## Telegram Config
  telegram:
    podo:
      bot:
        token: 451179803:AAGMt05UHAUE1p4veWRws2Wz93FmV5Plvwc
        name: PodoDevBot
      admin:
        id: 503609560

  ## Solr Config
  solr:
    url: http://192.168.219.103:8979/solr # Loopback
    core:
      id: podo-dev
    query:
      hl:
        pre:
          max:
            length: 100
        frag:
          length: 10000000
        simple:
          pre: ((start-search))
          post: ((end-search))



## Google Oauth
google:
  client:
    clientId: 644014618387-hd23qa0hrtqvbtnfb0u3c9o9q9duq970.apps.googleusercontent.com
    clientSecret: RxNajOBGU8TZtR-zc9pOu6uG
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

security:
  expire:
    time: 24 # Hours
  oauth2:
    admin:
      ids: 116440278738014640765, 116491882380204991899
    redirect: http://localhost:8118/#/


---

spring:
  profiles: deploy
  jpa:
    show-sql: false

logging:
  config: classpath:logback-daily.xml

local:
  sitemap:
    url: /web
    dir: /web
  upload:
    base:
      url: /uploaded
      dir: /uploaded

security:
  oauth2:
    admin:
    redirect: https://www.podo-dev.com/#/

---

spring:
  profiles: external

  datasource:
    url: jdbc:mysql://mysql.podo-dev.com/podo_dev?characterEncoding=UTF-8&serverTimezone=Asia/Seoul

infra:
  uploader:
    upload:
      domain: https://upload.podo-dev.com
  telegram:
    podo:
      bot:
        token: 963473619:AAF1412LpXDNNvN7gn6qcip88-z_DVLVEVU
  solr:
    url: http://solr.podo-dev.com

