#Server Config
server:
  port: 8090

# Paging
blog:
  per:
    page:
      size: 10

spring:
  # Data Resource
  datasource:
    url: jdbc:mysql://192.168.219.103:3307/podo-dev?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: cglee079
    password: lcg050179!
    driver-class-name: com.mysql.jdbc.Driver

  # Hibernate config
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format: false

  # Security
  security:
    user:
      name: cglee079
      password: s12345

logging:
  level:
    org:
      springframework:
        web: DEBUG


upload:
  base:
    url: /uploaded
    dir: C://podo-dev/upload
  postfix:
    image:
      dir: /blogs/images


#File Uploader
podo:
  uploader:
    domain: http://localhost:8092
    upload:
      image:
        subpath: /api/images
    frontend:
      subpath: /uploaded


#Telegram Notice Config
telegram:
  podo:
    bot:
      token: 509885308:AAGqgiMXRfkXWeamsta6N0nFkF0d9I_SFOI
    user:
      name: PodoDevBot
      id: 503609560
