###########################
##### RUN BUILD #####
###########################
FROM gradle:6.8.2-jdk8-openj9  AS builder

COPY . .

ARG SUB_MODULE

RUN chmod 777 gradlew
RUN ./gradlew --no-daemon --debug :${SUB_MODULE}:clean
RUN ./gradlew --no-daemon --debug -x test :${SUB_MODULE}:dependencies


