###########################
##### RUN BUILD #####
###########################
FROM gradle:6.8.2-jdk8

COPY --chown=gradle:gradle . /home/gradle/src

ARG SUB_MODULE

WORKDIR /home/gradle/src

RUN gradle --no-daemon --debug :${SUB_MODULE}:clean
RUN gradle --no-daemon --debug -x test :${SUB_MODULE}:dependencies


