#Server Config
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: s12345
    keyStoreType: PKCS12
    keyAlias: tomcat


uploader:
  security:
    client:
      tokens: mciGpOzzSvncQJ5IFEUNVODRyVkgL1kD