spring.profiles.include: secret, core


server.port: 38443
server.http.port: 38080

# Servlet
spring.servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB


storage.uploaded.dir: C://podo-dev/podo-dev-storage/uploaded

## Log
logging:
  file.name: podo-dev-storage.%d{yyyy-MM-dd}-%i.log
  file.path: c://podo-dev/podo-dev-storage/logs

---

spring:
  profiles: deploy

storage.uploaded.dir: /uploaded

logging:
  file.path: /data/logs




