spring.profiles.include: secret

server.port: 38443
server.http.port: 38080

## Log
logging:
  file.name: podo-dev-storage.%d{yyyy-MM-dd}-%i.log
  file.path: c://podo-dev/podo-dev-storage/logs

# Servlet
spring.servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB


storage:
  uploaded:
    dir: C://podo-dev/podo-dev-storage/uploaded

---

spring.profiles: deploy

server.port: 8443
server.http.port: 8080

storage:
  uploaded:
    dir: /uploaded

logging:
  file.path: /data/logs




