infra.storage:
  auth.token: mock
  server:
    internal: mock
  static:
    internal: mock
    external: mock
  #      external: https://static.podo-dev.com

infra.telegram:
  admin:
    telegram_id: mock
  bot:
    name: mock
    token: mock

infra.solr:
  url: mock
  core_id: mock
  highlight:
    pre_max_text_length: 100
    frag:
      length: 10000000

infra.git:
  auth.token: mock
  user.id: cglee079
  event.max_length : 7

infra.gmail:
  send.timeout: 5000
  admin:
    name: mock
    email: mock
    id: mock
    password: mock