
#Server Config
server:
  port: 8092


spring:
  profiles:
    include: 'core'

  # Servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


uploader:
  frontend:
    subpath: /uploaded
  upload:
    base:
#      dir: /upload
      dir: C://podo-dev-uploader/upload



