#Server Config
server:
  port: 38443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: s12345
    keyStoreType: PKCS12
    keyAlias: tomcat
  http:
    port: 38080

spring:
  profiles:
#    include: core
    include: core,deploy

  # Servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


uploader:
  security:
    client:
      tokens: mciGpOzzSvncQJ5IFEUNVODRyVkgL1kD
  frontend:
    subpath: /uploaded
  upload:
    base:
    #      dir: /upload
      dir: C://podo-dev-uploader/upload
---

spring:
  profiles: deploy
  jpa:
    show-sql: false

logging:
  config: classpath:logback-daily.xml

uploader:
  upload:
    base:
      dir: /uploaded



