#Server Config
server:
  port: 8080


spring:
  profiles:
    include: 'core'

  # Servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


uploader:
  security:
    client:
      tokens: mciGpOzzSvncQJ5IFEUNVODRyVkgL1kD
  frontend:
    subpath: /uploaded
  upload:
    base:
            dir: /upload
#      dir: C://podo-dev-uploader/upload



